import { londrina } from "@/ui/fonts";
import "../globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={londrina.className}>
      <main>{children}</main>
      </body>
    </html>
  )
}
